name: C/C++ CI

on:
  push:
    # After publish 'main' and 'develop'.
    branches:
      - main
      - develop
      
  pull_request:
    # Run tests for any PRs.
    branches: [ main ]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: image

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
